import PersonImage from '../../assets/personblack.jpg';
import CompanyIcon from '../../assets/companyLogo.png';
export const ClientsData = [
	{
		id: 1,
		name: { userName: 'Deal 1', notification: 3 },
		stage: 'discovery',
		assignee: PersonImage,
		value: 100000,
		contacts: ['mostafa Osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'high',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 100000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP', 'RFQ'],
	},
	{
		id: 2,
		name: { userName: 'Deal 2', notification: 0 },
		stage: 'proposal',
		assignee: null,
		value: 20000,
		contacts: ['mostafa osman'],
		client: 'mostafa osman',
		priority: 'low',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'outgoing',
		clientBudget: 20000,
		proposalSubmissionDate: '2023-06-29',
		files: [],
	},
	{
		id: 3,
		name: { userName: 'Deal 3', notification: 1 },
		stage: 'proposal',
		assignee: null,
		value: 50000,
		contacts: ['mostafa osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'medium',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP'],
	},
	{
		id: 4,
		name: { userName: 'Deal 4', notification: 0 },

		stage: 'won',
		assignee: CompanyIcon,
		value: 250000,
		contacts: ['mostafa osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'medium',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP'],
	},
	{
		id: 5,
		name: { userName: 'Deal 5', notification: 0 },
		stage: 'won',
		assignee: CompanyIcon,
		value: 250000,
		contacts: ['mostafa osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'medium',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP'],
	},
	{
		id: 6,
		name: { userName: 'Deal 6', notification: 0 },
		stage: 'negotiation',
		assignee: CompanyIcon,
		value: 350000,
		contacts: ['mostafa osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'high',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP'],
	},
	{
		id: 7,
		name: { userName: 'Deal 7', notification: 0 },
		stage: 'won',
		assignee: PersonImage,
		value: 55000,
		contacts: ['mostafa osman'],
		client: 'mostafa osman',
		priority: 'low',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP'],
	},
	{
		id: 8,
		name: { userName: 'Deal 8', notification: 0 },
		stage: 'discovery',
		assignee: PersonImage,
		value: 75000,
		contacts: ['mostafa osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'low',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: [''],
	},
	{
		id: 9,

		name: { userName: 'Deal 9', notification: 0 },
		stage: 'negotiation',
		assignee: PersonImage,
		value: 150000,
		contacts: ['mostafa osman', 'mostafa osman'],
		client: 'mostafa osman',
		priority: 'medium',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP', 'RFQ'],
	},
	{
		id: 10,
		name: { userName: 'Deal 10', notification: 0 },
		stage: 'lost',
		assignee: PersonImage,
		value: 50000,
		contacts: ['mostafa osman'],
		client: 'mostafa osman',
		priority: 'high',
		lastActivity: '2023-06-29',
		dueDate: '2023-06-29',
		note: 'note',
		opportunitySpace: [PersonImage, PersonImage],
		company: CompanyIcon,
		creationDate: '2023-06-29',
		incoming: 'incoming',
		clientBudget: 50000,
		proposalSubmissionDate: '2023-06-29',
		files: ['RFP', 'RFQ'],
	},
];
